import json,os
out="C:/Projects/_SHARED/tools/PrePromptEngine.html"
PROJ={}
PROJ['9soccer']={'path':'C:\Projects\90Soccer','gh':'royea-beep/9soccer','sb':'psxqlmgsifvsmiijkucu','vc':'9soccer','url':'9soccer.ftable.co.il','stack':'Next.js+TS+Tailwind v4+Supabase+Capacitor','mob':'capacitor','desc':'9Soccer'}
PROJ['caps']={'path':'C:\Projects\Caps','gh':'royea-beep/caps-poker','sb':'gxrpunvhjcrzqnitbqah','vc':'caps','url':'caps.ftable.co.il','stack':'Expo+TypeScript+Supabase','mob':'expo','desc':'Caps Poker'}
PROJ['wingman']={'path':'C:\Projects\Wingman','gh':'royea-beep/wingman','sb':'rndqegtkcuqichobzypz','vc':'wingman','url':'wingman.ftable.co.il','stack':'Expo+Prisma+Railway+Supabase','mob':'expo','desc':'Wingman'}
PROJ['analyzer']={'path':'C:\Projects\analyzer-standalone','gh':'royea-beep/analyzer','sb':'vjxqlqtlywovnbidovit','vc':'analyzer','url':'analyzer.ftable.co.il','stack':'Next.js+TS+Tailwind+Supabase','mob':None,'desc':'Analyzer'}
PROJ['postpilot']={'path':'C:\Projects\PostPilot','gh':'royea-beep/PostPilot','sb':'uiyqswnhrbfctafeihdh','vc':'postpilot','url':'postpilot.ftable.co.il','stack':'Next.js+TS+Neon+Supabase Auth','mob':None,'desc':'PostPilot'}
PROJ['keydrop']={'path':'C:\Projects\KeyDrop','gh':'royea-beep/KeyDrop','sb':None,'vc':None,'url':'keydrop.ftable.co.il','stack':'Next.js+TS+Prisma','mob':None,'desc':'KeyDrop'}
PROJ['explainit']={'path':'C:\Projects\ExplainIt','gh':'royea-beep/ExplainIt','sb':None,'vc':None,'url':'explainit.ftable.co.il','stack':'Next.js+TS+Playwright+Prisma','mob':None,'desc':'ExplainIt'}
PROJ['venuekit']={'path':'C:\Projects\VenueKit','gh':'royea-beep/VenueKit','sb':None,'vc':None,'url':'venuekit.ftable.co.il','stack':'Next.js+TS+Hebrew RTL','mob':None,'desc':'VenueKit'}
PROJ['ftable']={'path':'C:\Projects\ftable','gh':'royea-beep/ftable','sb':'uiyqswnhrbfctafeihdh','vc':None,'url':'ftable.co.il','stack':'Static HTML+JS+cPanel','mob':None,'desc':'ftable'}
PROJ['clubgg']={'path':'C:\Projects\clubgg','gh':'royea-beep/clubgg','sb':None,'vc':None,'url':'clubgg.ftable.co.il','stack':'Next.js+TS+Supabase','mob':None,'desc':'ClubGG'}
PROJ['letsmakebillions']={'path':'C:\Projects\letsmakebillions','gh':'royea-beep/letsmakebillions','sb':None,'vc':None,'url':None,'stack':'Next.js+Prisma+Railway','mob':None,'desc':'LetsMakeBillions'}

GEMS={'rls':{'l':'Supabase RLS','d':'Enable RLS + policy'},'mask':{'l':'CI Secret Masking','d':'GitHub Actions mask'},'venv':{'l':'Vercel Env CLI','d':'Add/remove env vars'},'dns':{'l':'cPanel DNS CNAME','d':'Add CNAME via cPanel'},'efn':{'l':'Edge Function Deploy','d':'Deploy Edge Function'},'prisma':{'l':'Prisma Version Fix','d':'Fix stale types'},'eslint':{'l':'ESLint Fix','d':'Fix ESLint after upgrade'},'timeout':{'l':'Timeout Guard','d':'AbortController 120s'}}
RULES=['RULE0: User NEVER does manual steps. Try 9+ API/CLI paths.','Hebrew with user, English for prompts.','Always use parallel agents.','FINAL REPORT with status per item.','Always: Yes, allow all edits in components','Auto-approve ALL steps.','No monetization suggestions unless asked.','Use Supabase API, cPanel UAPI, Vercel CLI, GitHub CLI.','Credentials in Heroes-Hadera memory and Caps/.env.','No Stripe - Payplus (IL) or LemonSqueezy (SaaS).']

CATS={'sec':{'n':'Security','i':'lock','dg':'אבטחה','t':[{'k':'sec-full','n':'Full Security Audit','d':'git history, RLS, env, headers'},{'k':'rls-fix','n':'RLS Fix','d':'Enable RLS on tables'},{'k':'secrets-scan','n':'Secrets Scan','d':'Leaked secrets in git'},{'k':'ci-hardening','n':'CI Hardening','d':'Mask secrets, branch protection'},{'k':'windows-hardening','n':'Windows Hardening','d':'ASR, Defender, CFA'}]},'health':{'n':'Health','i':'health','dg':'בריאות','t':[{'k':'health-full','n':'Full Health Scan','d':'Build, sites, Supabase, CI'},{'k':'build-fix','n':'Build Fix','d':'Fix broken builds'},{'k':'supabase-audit','n':'Supabase Audit','d':'Crons, RLS, Edge Functions'},{'k':'ci-fix','n':'CI Fix','d':'Fix failing GitHub Actions'},{'k':'env-sync','n':'Env Sync','d':'Sync .env.local vs Vercel'}]},'infra':{'n':'Infrastructure','i':'infra','dg':'תשתית','t':[{'k':'deploy-subdomain','n':'New Subdomain','d':'DNS+Vercel+SSL via cPanel'},{'k':'supabase-new','n':'Supabase Project','d':'Create, RLS, auth'},{'k':'github-setup','n':'GitHub Setup','d':'Branch protection, dependabot'},{'k':'testflight','n':'TestFlight Pipeline','d':'iOS CI/CD'}]},'game':{'n':'Game Dev','i':'game','dg':'פיתוח משחק','t':[{'k':'new-game-mode','n':'New Game Mode','d':'Logic+UI+DB+flag'},{'k':'game-balance','n':'Balance Tuning','d':'Scoring, timing, difficulty'},{'k':'creature-system','n':'Creature System','d':'DNA+evolution+unlocks'},{'k':'multiplayer','n':'Multiplayer','d':'Realtime+matchmaking'},{'k':'localization','n':'Localization','d':'HE/EN/AR/ES'},{'k':'app-store','n':'App Store Prep','d':'Screenshots, ASO'},{'k':'sprint-generic','n':'Generic Sprint','d':'General feature sprint'}]},'cross':{'n':'Cross-Project','i':'cross','dg':'בין פרויקטים','t':[{'k':'save-all','n':'Save Everything','d':'Knowledge, skills, DNA'},{'k':'cross-audit','n':'Cross Audit','d':'All projects health check'},{'k':'dep-cleanup','n':'Dep Cleanup','d':'Remove dead deps'}]},'cust':{'n':'Custom','i':'edit','dg':'מותאם','t':[{'k':'custom','n':'Custom Prompt','d':'Write your own task'}]}}
